{"hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"identifier":{"url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The type of error that can terminate the sequence.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" = "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"Failure","kind":"identifier"}],"roleHeading":"Type Alias","modules":[{"name":"FlowKit"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"role":"symbol","title":"AsyncThrowingSubject.Failure","symbolKind":"typealias","externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea"},"references":{"doc://flowkit.FlowKit/documentation/FlowKit":{"kind":"symbol","title":"FlowKit","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/flowkit"},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"navigatorTitle":[{"text":"Failure","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","kind":"symbol","abstract":[{"text":"The type of error that can terminate the sequence.","type":"text"}],"title":"AsyncThrowingSubject.Failure","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"type":"topic","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","title":"AsyncThrowingSubject","abstract":[{"type":"text","text":"A subject that allows for asynchronously sending values or terminating with an error."},{"type":"text","text":" "},{"type":"codeVoice","code":"AsyncThrowingSubject"},{"type":"text","text":" acts as a bridge between imperative code and asynchronous code, enabling"},{"text":" ","type":"text"},{"type":"text","text":"you to send values to an "},{"code":"AsyncSequence","type":"codeVoice"},{"text":" consumer while handling potential errors gracefully.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncThrowingSubject"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AsyncThrowingSubject","kind":"identifier"}]}}}