{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea","role":"symbol","roleHeading":"Type Alias","modules":[{"name":"FlowKit"}],"title":"AsyncThrowingSubject.Failure","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}],"navigatorTitle":[{"text":"Failure","kind":"identifier"}],"symbolKind":"typealias"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"kind":"text","text":" = "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"references":{"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"url":"\/documentation\/flowkit\/asyncthrowingsubject","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AsyncThrowingSubject"}],"navigatorTitle":[{"text":"AsyncThrowingSubject","kind":"identifier"}],"type":"topic","title":"AsyncThrowingSubject","kind":"symbol","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject","abstract":[{"text":"A subject that allows for asynchronously sending values or terminating with an error.","type":"text"},{"type":"text","text":" "},{"code":"AsyncThrowingSubject","type":"codeVoice"},{"type":"text","text":" acts as a bridge between imperative code and asynchronous code, enabling"},{"type":"text","text":" "},{"type":"text","text":"you to send values to an "},{"type":"codeVoice","code":"AsyncSequence"},{"text":" consumer while handling potential errors gracefully.","type":"text"}]},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"navigatorTitle":[{"kind":"identifier","text":"Failure"}],"role":"symbol","title":"AsyncThrowingSubject.Failure","type":"topic","abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"kind":"symbol","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"doc://flowkit.FlowKit/documentation/FlowKit":{"kind":"symbol","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","title":"FlowKit","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/flowkit"}}}