{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Alias","title":"AsyncThrowingSubject.Failure","modules":[{"name":"FlowKit"}],"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Failure"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Failure"}],"externalID":"s:7FlowKit20AsyncThrowingSubjectV7Failurea"},"hierarchy":{"paths":[["doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flowkit\/asyncthrowingsubject\/failure"]}],"sections":[],"abstract":[{"text":"The type of error that can terminate the sequence.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"},{"text":" = ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}]}],"kind":"declarations"}],"references":{"doc://flowkit.FlowKit/documentation/FlowKit":{"abstract":[],"kind":"symbol","url":"\/documentation\/flowkit","title":"FlowKit","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit","type":"topic","role":"collection"},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject/Failure":{"abstract":[{"type":"text","text":"The type of error that can terminate the sequence."}],"identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject\/Failure","title":"AsyncThrowingSubject.Failure","kind":"symbol","type":"topic","url":"\/documentation\/flowkit\/asyncthrowingsubject\/failure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Failure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"}]},"doc://flowkit.FlowKit/documentation/FlowKit/AsyncThrowingSubject":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncThrowingSubject"}],"url":"\/documentation\/flowkit\/asyncthrowingsubject","type":"topic","abstract":[{"text":"A subject that allows for asynchronously sending values or terminating with an error.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"AsyncThrowingSubject"},{"text":" acts as a bridge between imperative code and asynchronous code, enabling","type":"text"},{"type":"text","text":" "},{"text":"you to send values to an ","type":"text"},{"type":"codeVoice","code":"AsyncSequence"},{"text":" consumer while handling potential errors gracefully.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AsyncThrowingSubject"}],"title":"AsyncThrowingSubject","role":"symbol","identifier":"doc:\/\/flowkit.FlowKit\/documentation\/FlowKit\/AsyncThrowingSubject"}}}